name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - run: pip install -r requirements.txt

    - run: pytest

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
    - uses: actions/checkout@v4

    - run: docker build -t word-game .

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
    - name: Trigger Render Deployment
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
